### ISSUE TITLE
Startup script executes bootstrap exec command before docker has started Consul

### ISSUE THREAD

**Issue by dekobon** [autopilotpattern/consul#16]
We occasionally see this behavior in Triton:

```
➜  consul git:(master) ✗ ./start.sh 
Starting a Triton trusted Consul service

Pulling the most recent images
WARNING: The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Pulling consul (autopilotpattern/consul:latest)...
latest: Pulling from autopilotpattern/consul (req 270197e0-12e7-11e6-92bb-d5e1dd6ff0dc)
830450f9a5ce: Already exists
739eb5ccedb4: Already exists
1cc32231595a: Already exists
d992bfbda305: Already exists
9d710148acd0: Already exists
aa6a17e27f5d: Already exists
54bb751ceeaf: Already exists
7b395b5811af: Already exists
bea864120e95: Already exists
d6f8ca12a3d3: Already exists
0ad10db1c67b: Already exists
4858d6a328c1: Already exists
2f045885aafd: Already exists
fe7fdb07dbcb: Already exists
b51065e66662: Already exists
Digest: sha256:3dd3f730381654bd26b844b44675cf67a7d169c88257f3d7a53de2d149a03855
Status: Image is up to date for autopilotpattern/consul:latest

Starting containers
WARNING: The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Starting consul_consul_1

Waiting for the bootstrap instance.Error response from daemon: problem executing command (32dda270-12e7-11e6-92bb-d5e1dd6ff0dc)
...............................
```

When you check the request id against the server logs:

```
    HTTP/1.1 500 Internal Server Error
    content-type: text/plain
    content-length: 64
    date: Thu, 05 May 2016 17:31:29 GMT
    x-request-id: 32dda270-12e7-11e6-92bb-d5e1dd6ff0dc
    x-response-time: 863
    server: Triton/1.9.0 (linux)

    problem executing command (32dda270-12e7-11e6-92bb-d5e1dd6ff0dc)
    --
    DockerError: problem executing command; caused by InternalError: posting task to cn-agent: {"error":"docker_exec: VM is not running, cannot exec","details":{"restCode":"VmNotRunning"}}
        at DockerError._DockerBaseError (/opt/smartdc/docker/lib/errors.js:173:15)
        at new DockerError (/opt/smartdc/docker/lib/errors.js:194:22)
        at Object.cnapiErrorWrap (/opt/smartdc/docker/lib/errors.js:547:20)
        at _execCb (/opt/smartdc/docker/lib/backends/sdc/containers.js:3989:36)
        at /opt/smartdc/docker/node_modules/sdc-clients/lib/restifyclient.js:174:20
        at parseResponse (/opt/smartdc/docker/node_modules/sdc-clients/node_modules/restify/lib/clients/json_client.js:84:9)
        at IncomingMessage.done (/opt/smartdc/docker/node_modules/sdc-clients/node_modules/restify/lib/clients/string_client.js:151:17)
        at IncomingMessage.g (events.js:180:16)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
    Caused by: InternalError: posting task to cn-agent: {"error":"docker_exec: VM is not running, cannot exec","details":{"restCode":"VmNotRunning"}}
        at parseResponse (/opt/smartdc/docker/node_modules/sdc-clients/node_modules/restify/lib/clients/json_client.js:67:23)
        at IncomingMessage.done (/opt/smartdc/docker/node_modules/sdc-clients/node_modules/restify/lib/clients/string_client.js:151:17)
        at IncomingMessage.g (events.js:180:16)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:492:13)
    --
    req.timers: {
      "handler-0": 29,
      "bunyan": 48,
      "handler-2": 161,
      "checkReadonlyMode": 13,
      "checkServices": 16,
      "reqAuth": 950,
      "reqClientApiVersion": 56,
      "reqParamsId": 11,
      "getVm": 41262,
      "readBody": 543,
      "parseBody": 146,
      "containerExec": 820443
    }
```

The command that is failing is: https://github.com/autopilotpattern/consul/blob/master/start.sh#L36

Essentially, what the server error is saying is that the instance hasn't been started yet. This may be technically a bug with Triton, but it would be worthwhile to still put a sleep or some retry for this command because if the exec command doesn't succeed (even if it was a network blip), the rest of the commands will fail.

**Comment by tgross** [comment]
Just noting this bit will go away once we do https://github.com/autopilotpattern/consul/issues/14 and we won't need to do any `docker exec`. That being said, not a bad idea to add a sleep/retry loop.

**Comment by tgross** [comment]
Obviated by https://github.com/autopilotpattern/consul/pull/19
